version: 2
updates:
  - package-ecosystem: uv
    directories:
      - "*/**"
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
