# Use this config to run the otel collector locally (for testing)
# docker run -p 4317:4317 -p 4318:4318 --rm -v $(pwd)/otel-config.yaml:/etc/otelcol/config.yaml otel/opentelemetry-collector

# Otlp receiver configuration
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
          - "*"
          allowed_headers:
          - "*"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
