name: Build Data Quality Rules Monitor Image

on:
    push:
        branches:
            - main
            - feat/data-quality-rules-monitor
        paths:
            - "utilities/data_quality_rules_monitor/**"
            - "Dockerfile"
            - ".github/workflows/build-dq-rules-monitor.yaml"
            - "!**.md"
            - "!images/**"
            - "!**.png"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v4.0.0
              with:
                  fetch-depth: 0

            - name: Get short SHA
              id: short_sha
              run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

            - name: Lowercase branch name
              id: get_lowercase_branch
              run: echo "lowercase_branch=$(echo '${GITHUB_REF#refs/heads/}' | tr '[:upper:]' '[:lower:]' | tr '/' '-')" >> $GITHUB_OUTPUT

            - name: Set up Buildx
              id: buildx
              uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

            - name: Login to GitHub Registry
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.ORG_PAT_GITHUB }}

            - name: Build and push docker image
              id: ghcr_docker_build
              uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
              with:
                  context: ./utilities/data_quality_rules_monitor
                  file: ./utilities/data_quality_rules_monitor/Dockerfile
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/atlan-data-quality-rules-monitor:latest
                      ghcr.io/${{ github.repository_owner }}/atlan-data-quality-rules-monitor:${{ steps.short_sha.outputs.sha }}
              env:
                  DOCKER_CLIENT_TIMEOUT: 900
                  COMPOSE_HTTP_TIMEOUT: 900
