name: Test for security issues with Snyk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: uv sync --all-extras

    - name: create requirements.txt
      run: uv pip compile pyproject.toml -o requirements.txt

    - uses: snyk/actions/setup@master
    - name: Test dependencies with Snyk
      run: snyk test --file=requirements.txt
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}

    - name: Monitor dependencies for security issues with Snyk
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
